modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "webhooker"
version = "${version}"
displayName = "WebHooker"
authors = "Brodino"
description = "A simple API for sending discord messages using WebHooks"
#logoFile = ""

[[dependencies.webhooker]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.webhooker]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.webhooker]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.82,)"
ordering = "AFTER"
side = "BOTH"
