name: Build only

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Java 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Grant permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build