name: Update mod description

on:
  push:
    branches:
      - master
    paths:
      - "gradle.properties"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Setup python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.9"

      - name: Execute Python script
        run: scripts/update_mod_description.py

      - name: Commit files
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore(automation): updated fabric and forge mod description"